# Generated by Django 3.2.8 on 2021-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.TextField(),
        ),
    ]
