# Generated by Django 3.2.8 on 2021-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnips', '0004_auto_20211109_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='code',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
