# Generated by Django 3.2.8 on 2021-11-06 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codesnips', '0002_auto_20211106_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='language',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
