# Generated by Django 3.2.8 on 2021-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnips', '0003_saveddata_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
