# Generated by Django 3.2.8 on 2021-11-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesnips', '0006_auto_20211109_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
